// Gerado automaticamente. Indicativos telefonicos de todos os paises (ITU),
// com os nomes em portugues. Ordenado por nome do pais.

export const INDICATIVOS = [
  { pais: "Afeganistão", codigo: "+93" },
  { pais: "África do Sul", codigo: "+27" },
  { pais: "Albânia", codigo: "+355" },
  { pais: "Alemanha", codigo: "+49" },
  { pais: "Andorra", codigo: "+376" },
  { pais: "Angola", codigo: "+244" },
  { pais: "Anguila", codigo: "+1264" },
  { pais: "Antígua e Barbuda", codigo: "+1268" },
  { pais: "Arábia Saudita", codigo: "+966" },
  { pais: "Argélia", codigo: "+213" },
  { pais: "Argentina", codigo: "+54" },
  { pais: "Armênia", codigo: "+374" },
  { pais: "Aruba", codigo: "+297" },
  { pais: "Austrália", codigo: "+61" },
  { pais: "Áustria", codigo: "+43" },
  { pais: "Azerbaijão", codigo: "+994" },
  { pais: "Bahamas", codigo: "+1242" },
  { pais: "Bangladesh", codigo: "+880" },
  { pais: "Barbados", codigo: "+1246" },
  { pais: "Barein", codigo: "+973" },
  { pais: "Bélgica", codigo: "+32" },
  { pais: "Belize", codigo: "+501" },
  { pais: "Benin", codigo: "+229" },
  { pais: "Bermudas", codigo: "+1441" },
  { pais: "Bielorrússia", codigo: "+375" },
  { pais: "Bolívia", codigo: "+591" },
  { pais: "Bósnia e Herzegovina", codigo: "+387" },
  { pais: "Botsuana", codigo: "+267" },
  { pais: "Brasil", codigo: "+55" },
  { pais: "Brunei", codigo: "+673" },
  { pais: "Bulgária", codigo: "+359" },
  { pais: "Burquina Faso", codigo: "+226" },
  { pais: "Burundi", codigo: "+257" },
  { pais: "Butão", codigo: "+975" },
  { pais: "Cabo Verde", codigo: "+238" },
  { pais: "Camarões", codigo: "+237" },
  { pais: "Camboja", codigo: "+855" },
  { pais: "Canadá", codigo: "+1" },
  { pais: "Catar", codigo: "+974" },
  { pais: "Cazaquistão", codigo: "+7" },
  { pais: "Chade", codigo: "+235" },
  { pais: "Chile", codigo: "+56" },
  { pais: "China", codigo: "+86" },
  { pais: "Chipre", codigo: "+357" },
  { pais: "Cidade do Vaticano", codigo: "+39" },
  { pais: "Colômbia", codigo: "+57" },
  { pais: "Comores", codigo: "+269" },
  { pais: "Congo - Kinshasa", codigo: "+243" },
  { pais: "Coreia do Norte", codigo: "+850" },
  { pais: "Coreia do Sul", codigo: "+82" },
  { pais: "Costa do Marfim", codigo: "+225" },
  { pais: "Costa Rica", codigo: "+506" },
  { pais: "Croácia", codigo: "+385" },
  { pais: "Cuba", codigo: "+53" },
  { pais: "Curaçao", codigo: "+599" },
  { pais: "Dinamarca", codigo: "+45" },
  { pais: "Djibuti", codigo: "+253" },
  { pais: "Dominica", codigo: "+1767" },
  { pais: "Egito", codigo: "+20" },
  { pais: "El Salvador", codigo: "+503" },
  { pais: "Emirados Árabes Unidos", codigo: "+971" },
  { pais: "Equador", codigo: "+593" },
  { pais: "Eritreia", codigo: "+291" },
  { pais: "Eslováquia", codigo: "+421" },
  { pais: "Eslovênia", codigo: "+386" },
  { pais: "Espanha", codigo: "+34" },
  { pais: "Essuatíni", codigo: "+268" },
  { pais: "Estados Unidos", codigo: "+1" },
  { pais: "Estônia", codigo: "+372" },
  { pais: "Etiópia", codigo: "+251" },
  { pais: "Fiji", codigo: "+679" },
  { pais: "Filipinas", codigo: "+63" },
  { pais: "Finlândia", codigo: "+358" },
  { pais: "França", codigo: "+33" },
  { pais: "Gabão", codigo: "+241" },
  { pais: "Gâmbia", codigo: "+220" },
  { pais: "Gana", codigo: "+233" },
  { pais: "Geórgia", codigo: "+995" },
  { pais: "Gibraltar", codigo: "+350" },
  { pais: "Granada", codigo: "+1473" },
  { pais: "Grécia", codigo: "+30" },
  { pais: "Groenlândia", codigo: "+299" },
  { pais: "Guadalupe", codigo: "+590" },
  { pais: "Guam", codigo: "+1671" },
  { pais: "Guatemala", codigo: "+502" },
  { pais: "Guernsey", codigo: "+44" },
  { pais: "Guiana", codigo: "+592" },
  { pais: "Guiana Francesa", codigo: "+594" },
  { pais: "Guiné", codigo: "+224" },
  { pais: "Guiné Equatorial", codigo: "+240" },
  { pais: "Guiné-Bissau", codigo: "+245" },
  { pais: "Haiti", codigo: "+509" },
  { pais: "Honduras", codigo: "+504" },
  { pais: "Hong Kong, RAE da China", codigo: "+852" },
  { pais: "Hungria", codigo: "+36" },
  { pais: "Iêmen", codigo: "+967" },
  { pais: "Ilha Christmas", codigo: "+61" },
  { pais: "Ilha de Man", codigo: "+44" },
  { pais: "Ilha Norfolk", codigo: "+672" },
  { pais: "Ilhas Aland", codigo: "+358" },
  { pais: "Ilhas Cayman", codigo: "+1345" },
  { pais: "Ilhas Cocos (Keeling)", codigo: "+61" },
  { pais: "Ilhas Cook", codigo: "+682" },
  { pais: "Ilhas Faroé", codigo: "+298" },
  { pais: "Ilhas Geórgia do Sul e Sandwich do Sul", codigo: "+500" },
  { pais: "Ilhas Malvinas", codigo: "+500" },
  { pais: "Ilhas Marianas do Norte", codigo: "+1670" },
  { pais: "Ilhas Marshall", codigo: "+692" },
  { pais: "Ilhas Pitcairn", codigo: "+64" },
  { pais: "Ilhas Salomão", codigo: "+677" },
  { pais: "Ilhas Turcas e Caicos", codigo: "+1649" },
  { pais: "Ilhas Virgens Americanas", codigo: "+1340" },
  { pais: "Ilhas Virgens Britânicas", codigo: "+1284" },
  { pais: "Índia", codigo: "+91" },
  { pais: "Indonésia", codigo: "+62" },
  { pais: "Irã", codigo: "+98" },
  { pais: "Iraque", codigo: "+964" },
  { pais: "Irlanda", codigo: "+353" },
  { pais: "Islândia", codigo: "+354" },
  { pais: "Israel", codigo: "+972" },
  { pais: "Itália", codigo: "+39" },
  { pais: "Jamaica", codigo: "+1876" },
  { pais: "Japão", codigo: "+81" },
  { pais: "Jersey", codigo: "+44" },
  { pais: "Jordânia", codigo: "+962" },
  { pais: "Kosovo", codigo: "+383" },
  { pais: "Kuwait", codigo: "+965" },
  { pais: "Laos", codigo: "+856" },
  { pais: "Lesoto", codigo: "+266" },
  { pais: "Letônia", codigo: "+371" },
  { pais: "Líbano", codigo: "+961" },
  { pais: "Libéria", codigo: "+231" },
  { pais: "Líbia", codigo: "+218" },
  { pais: "Liechtenstein", codigo: "+423" },
  { pais: "Lituânia", codigo: "+370" },
  { pais: "Luxemburgo", codigo: "+352" },
  { pais: "Macau, RAE da China", codigo: "+853" },
  { pais: "Macedônia do Norte", codigo: "+389" },
  { pais: "Madagascar", codigo: "+261" },
  { pais: "Malásia", codigo: "+60" },
  { pais: "Malaui", codigo: "+265" },
  { pais: "Maldivas", codigo: "+960" },
  { pais: "Mali", codigo: "+223" },
  { pais: "Malta", codigo: "+356" },
  { pais: "Marrocos", codigo: "+212" },
  { pais: "Martinica", codigo: "+596" },
  { pais: "Maurício", codigo: "+230" },
  { pais: "Mauritânia", codigo: "+222" },
  { pais: "Mayotte", codigo: "+262" },
  { pais: "México", codigo: "+52" },
  { pais: "Mianmar (Birmânia)", codigo: "+95" },
  { pais: "Micronésia", codigo: "+691" },
  { pais: "Moçambique", codigo: "+258" },
  { pais: "Moldávia", codigo: "+373" },
  { pais: "Mônaco", codigo: "+377" },
  { pais: "Mongólia", codigo: "+976" },
  { pais: "Montenegro", codigo: "+382" },
  { pais: "Montserrat", codigo: "+1664" },
  { pais: "Namíbia", codigo: "+264" },
  { pais: "Nauru", codigo: "+674" },
  { pais: "Nepal", codigo: "+977" },
  { pais: "Nicarágua", codigo: "+505" },
  { pais: "Níger", codigo: "+227" },
  { pais: "Nigéria", codigo: "+234" },
  { pais: "Niue", codigo: "+683" },
  { pais: "Noruega", codigo: "+47" },
  { pais: "Nova Caledônia", codigo: "+687" },
  { pais: "Nova Zelândia", codigo: "+64" },
  { pais: "Omã", codigo: "+968" },
  { pais: "Países Baixos", codigo: "+31" },
  { pais: "Países Baixos Caribenhos", codigo: "+599" },
  { pais: "Palau", codigo: "+680" },
  { pais: "Panamá", codigo: "+507" },
  { pais: "Papua-Nova Guiné", codigo: "+675" },
  { pais: "Paquistão", codigo: "+92" },
  { pais: "Paraguai", codigo: "+595" },
  { pais: "Peru", codigo: "+51" },
  { pais: "Polinésia Francesa", codigo: "+689" },
  { pais: "Polônia", codigo: "+48" },
  { pais: "Porto Rico", codigo: "+1787" },
  { pais: "Portugal", codigo: "+351" },
  { pais: "Quênia", codigo: "+254" },
  { pais: "Quirguistão", codigo: "+996" },
  { pais: "Quiribati", codigo: "+686" },
  { pais: "Reino Unido", codigo: "+44" },
  { pais: "República Centro-Africana", codigo: "+236" },
  { pais: "República do Congo", codigo: "+242" },
  { pais: "República Dominicana", codigo: "+1809" },
  { pais: "Reunião", codigo: "+262" },
  { pais: "Romênia", codigo: "+40" },
  { pais: "Ruanda", codigo: "+250" },
  { pais: "Rússia", codigo: "+7" },
  { pais: "Saara Ocidental", codigo: "+212" },
  { pais: "Samoa", codigo: "+685" },
  { pais: "Samoa Americana", codigo: "+1684" },
  { pais: "San Marino", codigo: "+378" },
  { pais: "Santa Helena", codigo: "+290" },
  { pais: "Santa Lúcia", codigo: "+1758" },
  { pais: "São Bartolomeu", codigo: "+590" },
  { pais: "São Cristóvão e Névis", codigo: "+1869" },
  { pais: "São Martinho", codigo: "+590" },
  { pais: "São Pedro e Miquelão", codigo: "+508" },
  { pais: "São Tomé e Príncipe", codigo: "+239" },
  { pais: "São Vicente e Granadinas", codigo: "+1784" },
  { pais: "Seicheles", codigo: "+248" },
  { pais: "Senegal", codigo: "+221" },
  { pais: "Serra Leoa", codigo: "+232" },
  { pais: "Sérvia", codigo: "+381" },
  { pais: "Singapura", codigo: "+65" },
  { pais: "Sint Maarten", codigo: "+1721" },
  { pais: "Síria", codigo: "+963" },
  { pais: "Somália", codigo: "+252" },
  { pais: "Sri Lanka", codigo: "+94" },
  { pais: "Sudão", codigo: "+249" },
  { pais: "Sudão do Sul", codigo: "+211" },
  { pais: "Suécia", codigo: "+46" },
  { pais: "Suíça", codigo: "+41" },
  { pais: "Suriname", codigo: "+597" },
  { pais: "Svalbard e Jan Mayen", codigo: "+47" },
  { pais: "Tadjiquistão", codigo: "+992" },
  { pais: "Tailândia", codigo: "+66" },
  { pais: "Taiwan", codigo: "+886" },
  { pais: "Tanzânia", codigo: "+255" },
  { pais: "Tchéquia", codigo: "+420" },
  { pais: "Território Britânico do Oceano Índico", codigo: "+246" },
  { pais: "Territórios palestinos", codigo: "+970" },
  { pais: "Timor-Leste", codigo: "+670" },
  { pais: "Togo", codigo: "+228" },
  { pais: "Tokelau", codigo: "+690" },
  { pais: "Tonga", codigo: "+676" },
  { pais: "Trinidad e Tobago", codigo: "+1868" },
  { pais: "Tunísia", codigo: "+216" },
  { pais: "Turcomenistão", codigo: "+993" },
  { pais: "Turquia", codigo: "+90" },
  { pais: "Tuvalu", codigo: "+688" },
  { pais: "Ucrânia", codigo: "+380" },
  { pais: "Uganda", codigo: "+256" },
  { pais: "Uruguai", codigo: "+598" },
  { pais: "Uzbequistão", codigo: "+998" },
  { pais: "Vanuatu", codigo: "+678" },
  { pais: "Venezuela", codigo: "+58" },
  { pais: "Vietnã", codigo: "+84" },
  { pais: "Wallis e Futuna", codigo: "+681" },
  { pais: "Zâmbia", codigo: "+260" },
  { pais: "Zimbábue", codigo: "+263" },
];

